# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

id: hl7.fhir.us.immds
canonical: http://hl7.org/fhir/us/immds
version: 2.0.0
name: ImmunizationDecisionSupportForecastImmDSImplementationGuide
title: Immunization Decision Support Forecast (ImmDS) Implementation Guide
description: An IG for querying a decision support engine for a personalized immunization forecast.
status: active
publisher: 
  name: HL7 International / Public Health
  url: http://www.hl7.org/Special/committees/pher
contact:
  - name: Nathan Bunker
    telecom:
      - system: email
        value: mailto:nbunker@immregistry.org
license: CC0-1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 3.1.0  # <TO DO> do we need to update this to at least the USCDI v3 representation in US Core?
parameters:
  show-inherited-invariants: false
jurisdiction: urn:iso:std:iso:3166#US
copyrightYear: 2020+
releaseLabel: ci-build

extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 3
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: pher

pages:
  index.md:
    title: Home
  Guidance.md:
    title: Guidance
  UseCases.md:
    title: Use Cases
  Download.md:
    title: Download
  changes.md:
    title: Change Log
    

menu:
  Home: index.html
  Backgound: 
    Guidance: Guidance.html
    Use Cases: UseCases.html
  Artifacts Summary: artifacts.html
  Change Log: changes.html
